# Generated by Django 4.2 on 2025-07-26 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutout_id', models.CharField(max_length=50)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date_taken'],
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('settings', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('from_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_transitions', to='timelines.keyphoto')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timelines.timeline')),
                ('to_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_transitions', to='timelines.keyphoto')),
            ],
        ),
        migrations.AddField(
            model_name='keyphoto',
            name='timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_photos', to='timelines.timeline'),
        ),
    ]
