# Generated by Django 4.2 on 2025-07-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transition',
            name='from_photo',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='timeline',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='to_photo',
        ),
        migrations.RenameField(
            model_name='timeline',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AddField(
            model_name='timeline',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='KeyPhoto',
        ),
        migrations.DeleteModel(
            name='Transition',
        ),
    ]
