# Generated by Django 4.2 on 2025-07-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0003_timelinetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelinetype',
            name='user',
        ),
    ]
