# Generated by Django 4.2 on 2025-07-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0004_remove_timelinetype_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='user',
        ),
    ]
