# Generated by Django 4.2 on 2025-08-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0005_remove_timeline_settings_remove_timeline_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('s3_path', models.CharField(max_length=500)),
                ('s3_url', models.URLField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('photo_taken_at', models.DateTimeField()),
                ('weight_centigrams', models.IntegerField()),
                ('file_size', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
