# Generated by Django 4.2 on 2025-08-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0006_keyphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyphoto',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
