# Generated by Django 4.2 on 2025-08-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0007_alter_keyphoto_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyphoto',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
