# Generated by Django 4.2 on 2025-08-05 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0008_keyphoto_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyphoto',
            old_name='s3_url',
            new_name='presigned_url',
        ),
        migrations.RemoveField(
            model_name='keyphoto',
            name='content_type',
        ),
    ]
