# Generated by Django 4.2 on 2025-08-12 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timelines', '0009_rename_s3_url_keyphoto_presigned_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyphoto',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeline',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='keyphoto',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='keyphoto',
            unique_together={('user', 'filename')},
        ),
        migrations.AlterUniqueTogether(
            name='timeline',
            unique_together={('user', 'name')},
        ),
    ]
